version: '3'
services:
  web:
    build: .
    ports:
      - "8000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
        - .:/app
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
